# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2708af42a0dad9b193dafe5ea0c37bbd33a8b0854210655a6c2dfe96b834d7a54397059414331e96992af12e8ca7945c7e9f4657d856859dc04182ee60a0f492

test:
  secret_key_base: 9c9cd88777d41ccaf36dc8b2051d94139166e87c87f0071d5d52add859915e31edde62d6b6f40270a1f67337ed85312740fcc35168bd759ed1018031df1373d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
